name: Test PR on Flix Nightly

on:
  pull_request:
    branches: [ master ]

jobs:
  build-nightly:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      uses: mlutze/flix-action-templates/.github/workflows/flix-test.yaml@master
      with:
        flix: nightly